### ISSUE TITLE
V72 engines_build.py

### ISSUE THREAD

**Issue by Laterunner** [jromang/picochess#202]
Hi developers, I just tried to update/install pico 072 to my Odroid XU running lubuntu 14.4.4 (git clone --branch master ......) , but cannot start picochess any more: "engine_build.py" fails and no working stockfish is the the engine directory. 

My system is working with pico 071 - no problems

Kind regards Laterunner

**Comment by Laterunner** [comment]
**Here the screen output after python3 engine_build.py**

/opt/picochess72x/engines/armv7l/a-stockf: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/picochess72x/engines/armv7l/a-stockf)
ERROR:root:OS error in starting engine
Traceback (most recent call last):
  File "/opt/picochess72x/engine.py", line 191, in __init__
    self.engine.uci()
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 910, in uci
    return self._queue_command(command, async_callback)
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 890, in _queue_command
    return future.result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 402, in result
    return self.__get_result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 904, in command
    self.send_line("uci")
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 519, in send_line
    return self.process.send_line(line)
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 405, in send_line
    self.process.stdin.write("\n")
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 880, in _queue_command
    future = self.pool.submit(command)
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 99, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_engines.py", line 22, in <module>
    write_engine_ini()
  File "/opt/picochess72x/engine.py", line 114, in write_engine_ini
    engine.quit()
  File "/opt/picochess72x/engine.py", line 241, in quit
    return self.engine.quit()
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 1292, in quit
    return self._queue_command(command, async_callback)
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 882, in _queue_command
    raise EngineTerminatedException()
chess.uci.EngineTerminatedException

**Comment by djdekker** [comment]
Are you missing libstdc++?

**Comment by Laterunner** [comment]
Hi DJdekker, thx for reply
No, I did not find this. I did the manual installation on my odroid and up to now I did not need this package. 
When I now try to manually install this (apt-get install libstdc++) I get an errors  and libstdc++ is not installable. My ubuntu distribution is 14.04.5 LTS. So far I never had problems installing picochess
Kind regards Marius

**Comment by LocutusOfPenguin** [comment]
Hi Laterunner,

you can try to run INSIDE yr engines folder : "ldd ?-*" and look for errors (= not found lib). remove/move away these files, and try again (hopefully not all engines have this problem). This should work with limited engines (for the moment!)
OR:
You can download the sources of the provided engines, compile that yourself and put these files in engines folder (more complex, i would try above first).
At bonus, only do this for the moved away files from above.

Thats a quick fix, not the best - but since i dont have yr hardware, i can only help abit.

Jürgen

**Comment by Laterunner** [comment]
Ok. thank you for your reply. Not a hardware problem, an update problem : 
sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
sudo apt-get update
sudo apt-get upgrade
**sudo apt-get dist-upgrade**

did the job. V72 is running now
So thank you for help
Laterunner

**Comment by Laterunner** [comment]
Issue can be closed
